### ISSUE TITLE
casp14 result

### ISSUE THREAD

**Issue by TianjieY** [RosettaCommons/RoseTTAFold#1]
This is a wonderful job. But I have two questions. 

### This picture is the result of the evaluation of casp14.
![](https://www.biorxiv.org/content/biorxiv/early/2021/06/15/2021.06.14.448402/F1.large.jpg?width=800&height=600&carousel=1)

1. Do you only use UniRef30_2020_06 and bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt database to search MSAs?
2. Do you only use pdb100_2021Mar03 database to search templates(with above MSAs)?

**Comment by minkbaek** [comment]
For the CASP14 benchmark, we used a template database and sequence databases created before the CASP14 experiments. For template database, we used the pdb100 version created in March, 2020. For sequence database, we used BFD and UniRef30_2020_03.

**Comment by jiaxiang-wu** [comment]
Hi minkbaek, do you have any plans on releasing the PDB100 database created in March, 2020? This would help a lot for CASP14-related experiments.

**Comment by minkbaek** [comment]
You can find it here: https://files.ipd.uw.edu/pub/trRosetta2/pdb100_2020Mar11.tar.gz

**Comment by jiaxiang-wu** [comment]
Great! Thanks so much!
