### ISSUE TITLE
How to use 2 track network?

### ISSUE THREAD

**Issue by what-is-what** [RosettaCommons/RoseTTAFold#101]
As the instruction of usage shows, the output of 2track network for eukaryotes is complex.npz file. 
This just shows a distogram probability(maybe..?).
But the paper shows that we can predict its model using 2track.
How can we predict its structure using 2track network?

**Comment by ragunyrasta** [comment]
Did you mean 3track? Or 2track?

**Comment by Lsz-20** [comment]
> 
Have you solved this Problem? the same problem~
Thanks!

**Comment by Lsz-20** [comment]
@runitralph  
Some differences understand what you mean?
the 2 track has only has the output with the npz?
3track is ?
Thanks!

**Comment by runitralph** [comment]
> @runitralph  
> Some differences understand what you mean?
> the 2 track has only has the output with the npz?
> 3track is ?
> Thanks!

I think I've been tagged incorrectly here 😅

**Comment by Lsz-20** [comment]
> > @runitralph
> > Some differences understand what you mean?
> > the 2 track has only has the output with the npz?
> > 3track is ?
> > Thanks!
> 
> I think I've been tagged incorrectly here 😅

kk that's OK.Maybe do you know this question?

**Comment by runitralph** [comment]
> > > @runitralph
> > > Some differences understand what you mean?
> > > the 2 track has only has the output with the npz?
> > > 3track is ?
> > > Thanks!
> > 
> > I think I've been tagged incorrectly here 😅
> 
> kk that's OK.Maybe do you know this question?

I don't understand the question, and don't know what the answer would be.

**Comment by Lsz-20** [comment]
Thanks~
