### ISSUE TITLE
CUDA compatibility

### ISSUE THREAD

**Issue by huhlim** [RosettaCommons/RoseTTAFold#11]
I have an older version of the NVIDIA driver (450.36), which does not support CUDA toolkit >= 11.1 ([CUDA compatibility](https://docs.nvidia.com/deploy/cuda-compatibility/index.html#:~:text=Table%201.%20CUDA,%3E%3D%20346.46))
In such cases, network/predict_*.py scripts failed to run smoothly using GPUs because of the compatibility issue. 

Do the script really necessary to be run with the CUDA toolkit=11.1? When I created another RoseTTAFold conda environment with 
- cudatoolkit=10.2
- pytorch=1.8.1 (it could be 1.9.0, but I was using 1.8.1, so I tested with it.)

, the scripts seem to work fine. 
Someone who struggles with the same issue may use this [YAML file](https://raw.githubusercontent.com/huhlim/RoseTTAFold/main/RoseTTAFold-linux-cu101.yml) for the RoseTTAFold conda environment creation.

**Comment by minkbaek** [comment]
Yes, CUDA 10.2 should also work fine. Thanks for making YAML file with CUDA 10.2. I'll include this file in the repo.

**Comment by moonblue333** [comment]
CUDA 10.1 is OK.
