### ISSUE TITLE
How to find some introductions about these packages?

### ISSUE THREAD

**Issue by HectorTo** [RosettaCommons/RoseTTAFold#121]
Thanks for sharing Rosetta here! 
There are many executable binaries in this fold"bin" downloaded, to use these, do I need different orders for each?How to find them?
eg. package like **_relax.static.linuxgccrelease_** ,to use it, I must set 
-nstruct 2
-relax:default_repeats 25
-out:path:pdb .
-out:path:score .

so what about others?

**Comment by roccomoretti** [comment]
This repo is not Rosetta, the protein modeling package that's been around for several decades, but rather RoseTTAFold, the protein structure prediction neural-network published in 2021 (Baek et al. "Accurate prediction of protein structures and interactions using a three-track neural network" https://doi.org/10.1126/science.abj8754)

For "regular" Rosetta (the one with relax.static.linuxgccrelease), please see https://www.rosettacommons.org/  For the documentation, https://www.rosettacommons.org/docs/latest/  and if you have additional questions https://www.rosettacommons.org/forum

**Comment by HectorTo** [comment]
thanks a lot
