### ISSUE TITLE
pyrosetta.rosetta.utility.graph.EdgeListConstItera' object has no attribute '__mul__'

### ISSUE THREAD

**Issue by jiepan1** [RosettaCommons/RoseTTAFold#135]
PyRosetta-4 2023 [Rosetta PyRosetta4.conda.linux.cxx11thread.serialization.CentOS.python37.Release 2023.11+release.fe5f8333f1cbc3d246e74df5f7017adc23e83bcb 2023-03-13T07:57:24] retrieved from: http://www.pyrosetta.org
(C) Copyright Rosetta Commons Member Institutions. Created in JHU by Sergey Lyskov and PyRosetta Team.
/home/panjie/projects/tools/RoseTTAFold/RoseTTAFold-main/DAN-msa/models/smTr
While processing /home/panjie/projects/tools/RoseTTAFold/RoseTTAFold-main/example/pdb-3track/model0_1_0.25.features.npz: 'pyrosetta.rosetta.utility.graph.EdgeListConstItera' object has no attribute '__mul__'

**Comment by rmarabini** [comment]
I have the same question. Did you find out how to solve this?

**Comment by jiepan1** [comment]
yes,You uninstall your installation package for pyrosetta and install it with pip instead of conda

**Comment by rmarabini** [comment]
Uhm, that trick does not work for me :-(. Could you tell me which version of pyrosetta are you using? I will try to install the very same one. Do you install form the wheel packages or from the repository?

   Thanks

**Comment by jiepan1** [comment]
python3.8, I install from the repository ，there are my packages:
Package               Version
--------------------- -------------------
biopython             1.78
brotlipy              0.7.0
certifi               2022.12.7
cffi                  1.14.5
chardet               4.0.0
cryptography          3.4.7
cutadapt              4.1
decorator             5.1.1
dgl-cu110             0.6.1
dnaio                 0.9.0
googledrivedownloader 0.4
idna                  2.10
isal                  0.11.1
Jinja2                3.0.1
joblib                1.0.1
MarkupSafe            2.0.1
mkl-fft               1.3.0
mkl-random            1.2.1
mkl-service           2.3.0
networkx              2.5
numpy                 1.20.2
olefile               0.46
packaging             20.9
pandas                1.2.5
Pillow                8.2.0
pip                   21.1.3
pycparser             2.20
pyOpenSSL             20.0.1
pyparsing             2.4.7
PySocks               1.7.1
python-dateutil       2.8.1
python-louvain        0.15
pytz                  2021.1
requests              2.25.1
scikit-learn          0.24.2
scipy                 1.6.2
setuptools            52.0.0.post20210125
setuptools-scm        7.0.5
six                   1.16.0
threadpoolctl         2.1.0
tomli                 2.0.1
torch                 1.9.0
torch-cluster         1.5.9
torch-geometric       1.7.2
torch-scatter         2.0.7
torch-sparse          0.6.10
torch-spline-conv     1.2.1
torchaudio            0.9.0a0+33b2469
torchvision           0.10.0
tqdm                  4.61.1
typing-extensions     3.10.0.0
urllib3               1.26.6
wheel                 0.36.2
xopen                 1.5.0

**Comment by rmarabini** [comment]
Hi @jiepan1,

   I really appreciate your help with rosettafold ;-).  Rosettafold provides two scripts called run_e2e_ver.sh and run_pyrosetta_ver.sh. I have no problem executing the first one but I get the above mentioned error with the second one. The difference between these two scripts is that in the second one pyrosetta is used. I understand that run_pyrosetta_ver.sh requires tensorflow-gpu but this module is not in your package version list.  Am I missing something?

  cheers

**Comment by jiepan1** [comment]
sorry  But I can run run_pyrosetta_ver.sh  normally in cpu  
(RoseTTAFold) [panjie@cpu9 RoseTTAFold-main]$ bash run_pyrosetta_ver.sh example/input.fa .
Running HHblits
Running PSIPRED
Running hhsearch
Predicting distance and orientations
Running parallel RosettaTR.py
Running DeepAccNet-msa

**Comment by brianush1** [comment]
For anyone else having this issue, you can do a hotfix by modifying DAN-msa/pyErrorPred/featurize.py:

Line 81: `edge = iru.__mul__()` → `edge = iru.dereference()`
Line 102: `iru.plus_plus()` → `iru.pre_increment()`

**Comment by yrq3027** [comment]
> For anyone else having this issue, you can do a hotfix by modifying DAN-msa/pyErrorPred/featurize.py:
> 
> Line 81: `edge = iru.__mul__()` → `edge = iru.dereference()` Line 102: `iru.plus_plus()` → `iru.pre_increment()`

Thank you. It's worked.
