### ISSUE TITLE
hhsearch Segmentation fault 

### ISSUE THREAD

**Issue by moonblue333** [RosettaCommons/RoseTTAFold#2]
I tried these installation-packages or compiled version, all of them are segmentation fault.

#hh-suite
#wget https://github.com/soedinglab/hh-suite/releases/download/v3.3.0/hhsuite-3.3.0-SSE2-Linux.tar.gz
#tar xvfz hhsuite-3.3.0-SSE2-Linux.tar.gz

#wget https://github.com/soedinglab/hh-suite/releases/download/v3.3.0/hhsuite-3.3.0-AVX2-Linux.tar.gz
#tar xvfz hhsuite-3.3.0-AVX2-Linux.tar.gz

#wget https://mmseqs.com/hhsuite/hhsuite-linux-avx2.tar.gz --no-check-certificate
#tar xvfz hhsuite-linux-avx2.tar.gz

wget https://github.com/soedinglab/hh-suite/archive/refs/heads/master.zip --no-check-certificate
unzip hh-suite-master.zip
mv hh-suite-master hhsuite
cd hhsuite
mkdir -p ./build && cd ./build
apt install cmake
cmake -DCMAKE_INSTALL_PREFIX=.. ..
make -j 12
make install

**Comment by jiaxiang-wu** [comment]
If the segmentation fault is encountered during the hhsearch procedure (search against the template database), you may refer to this [issue](https://github.com/soedinglab/hh-suite/issues/275) for help. In short, the `_a3m` database is missing so the `-premerge` argument would lead to a failure. Compiling from the latest code from hh-suite's master branch should fix this issue.

**Comment by moonblue333** [comment]
Thanks @jiaxiang-wu.
This is OK for me.
wget https://github.com/soedinglab/hh-suite/releases/download/v3.2.0/hhsuite-3.2.0-AVX2-Linux.tar.gz --no-check-certificate
tar xvfz hhsuite-3.2.0-AVX2-Linux.tar.gz

**Comment by moonblue333** [comment]
workaround, close.

**Comment by moonblue333** [comment]
workaround, close.
