### ISSUE TITLE
network/predict_e2e.py might exist a little error?

### ISSUE THREAD

**Issue by CiaoHe** [RosettaCommons/RoseTTAFold#26]
Hi, 
I'm reading your code, and find one place might be typo:
`input_t2d = t2d[:,:,sel][:,:,:,sel].to(self.device)`
https://github.com/RosettaCommons/RoseTTAFold/blob/d0de739a1ef9193ff1c671a646683ffe5979b56b/network/predict_e2e.py#L174

I think it should be `input_t2d = t2d[:,:,sel][:,sel].to(self.device)` or else? Sorry for my poor skill of using index...

**Comment by minkbaek** [comment]
the t2d tensor has a size of (Batch, Templ, Length, Length, Features).  "sel" variable is the selected residues for the current crop, and the current index is right.
