### ISSUE TITLE
Type error from pyrosetta

### ISSUE THREAD

**Issue by mukhyala** [RosettaCommons/RoseTTAFold#28]
Hi,

I am using pyrosetta4 and line 86 in folding/utils.py :
`spline = rosetta.core.scoring.func.SplineFunc("", 1.0, 0.0, step, x,y)`
throws the following error:
```
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. pyrosetta.rosetta.core.scoring.func.SplineFunc()
    2. pyrosetta.rosetta.core.scoring.func.SplineFunc(arg0: pyrosetta.rosetta.core.scoring.func.SplineFunc)
    3. pyrosetta.rosetta.core.scoring.func.SplineFunc(arg0: pyrosetta.rosetta.core.scoring.func.SplineFunc)
```
Is there a PyRosetta4 version issue here?

**Comment by roccomoretti** [comment]
There's potentially is a version issue. "PyRosetta4" is updated semi-regularly. If you're using a version from 2019 or before, you'll likely encounter that error message for that line. You can check your PyRosetta version by running `import pyrosetta; print( pyrosetta.version() )` from within the Python interpreter you have it installed on. Somewhere on the line should be something like "2021.21+release.....", which identifies the build. The first number is the year, and if it's 2019 or before, I'd recommend updating PyRosetta.

**Comment by mukhyala** [comment]
Yes, as suggested, updating pyrosetta4 to 2021.27+release fixes this issue. Thanks for your help!
