### ISSUE TITLE
Last step of installation

### ISSUE THREAD

**Issue by idmjky** [RosettaCommons/RoseTTAFold#29]
Hi, 
I am trying to install the RoseTTAfold on a Linux based cluster, and I am at the last step of the installation
6. Obtain a PyRosetta licence and install the package in the newly created folding conda environment (link).

I am a little confused which package to use and how would I configure the install at this step. Do you mind giving a little more clarification on this please?
Thanks,
Albert

**Comment by roccomoretti** [comment]
The particular package of PyRosetta to use depends on your platform (OS) and the version of Python that you're installing it on. If you're installing RoseTTAFold into a Conda environment, installing with Conda (https://www.pyrosetta.org/downloads#h.c0px19b8kvuw) is probably the easiest, if it works for you. (Update your config as specified, then just run `conda install pyrosetta` from within the same environment you've installed RoseTTAFold to.)

**Comment by idmjky** [comment]
Hi, 
Thank for the instruction. I modified my condarc file to include the link, but when I tried installing it, I get the error message below. 

(folding) -bash-4.2$ conda install pyrosetta
Collecting package metadata (current_repodata.json): failed

CondaHTTPError: HTTP 401 UNAUTHORIZED for url <https://conda.graylab.jhu.edu/linux-64/current_repodata.json>
Elapsed: 00:00.148321

**Comment by roccomoretti** [comment]
The USERNAME & PASSWORD entries in the instructions need to be substituted with the username and password you received when you signed up for a PyRosetta license (see https://www.rosettacommons.org/software/license-and-download). If you did do the substitution, double check the entries, keeping in mind that they're case sensitive.

**Comment by idmjky** [comment]
I did replace the entries and checked the login details several times. However, I can not successfully download the software through anaconda. Is there an alternative route to try download and install?
