### ISSUE TITLE
PDB100 database compatability issues

### ISSUE THREAD

**Issue by martin-steinegger** [RosettaCommons/RoseTTAFold#3]
Multiple users having issues using the PDB100 database with HHblits (v3.3) (see https://github.com/soedinglab/hh-suite/issues/275). I noticed that PDB100 does not contain the the `_a3m` database. This causes the per-merge to crash. 
Is there any reason to not include the a3m file?

**Comment by minkbaek** [comment]
Oh, we simply didn't include it due to the file size (*a3m.ffdata: 634G). It seems its essential for hhblits v3.3. We'll definitely update the pdb100 database to include *_a3m.ff[data,index] file.

**Comment by martin-steinegger** [comment]
Thank you for the fast answer. Its a a fair point that the files size is too huge. 
You could probably run `hhfilter` to reduce it significantly.
We will also change the behavior of hhsearch/hhblits and printing a warning instead of crashing.

**Comment by moonblue333** [comment]
This is OK for this issue:
wget https://github.com/soedinglab/hh-suite/releases/download/v3.2.0/hhsuite-3.2.0-AVX2-Linux.tar.gz --no-check-certificate
tar xvfz hhsuite-3.2.0-AVX2-Linux.tar.gz

**Comment by minkbaek** [comment]
I've updated pdb100 databases (both 2021Mar03 and 2020Mar11 version) with *_a3m.ff[data,index] files.

**Comment by yoonsquared** [comment]
Hello @minkbaek, 
Sorry for re-opening what seems like a closed issue.
However, I am having a bit of trouble running RosettaFold.

It may be simple as making an ffindex file for the 
_pdb100_2021Mar03/pdb100_2021Mar03_cs219.ffdata_

But from the github (https://github.com/RosettaCommons/RoseTTAFold) where we 'wget' this link:
```
wget https://files.ipd.uw.edu/pub/RoseTTAFold/pdb100_2021Mar03.tar.gz
tar xfz pdb100_2021Mar03.tar.gz
```
There is no ffindex file for cs219 (along with _pdb100_2021Mar03_pdb.ffdata_ file)
Can I just make the ffindex file using the codes in this github?
https://github.com/soedinglab/ffindex_soedinglab   which @martin-steinegger  is also participating in?
