### ISSUE TITLE
Can it work on Windows?

### ISSUE THREAD

**Issue by ZhaoPengpeng1116** [RosettaCommons/RoseTTAFold#30]
I only have a Windows laptop. Will this work on Windows system?

**Comment by Wenzhe-Ma** [comment]
The pre-compiled codes are for linux. I don't think can run it on Windows now.

**Comment by minkbaek** [comment]
It's not supporting Windows.

**Comment by ZhaoPengpeng1116** [comment]
> The pre-compiled codes are for linux. I don't think can run it on Windows now.

Thanks

**Comment by ZhaoPengpeng1116** [comment]
> It's not supporting Windows.
Thanks
