### ISSUE TITLE
CONDA Environment

### ISSUE THREAD

**Issue by idmjky** [RosettaCommons/RoseTTAFold#34]
Hi, 
I followed the installation using conda and installed the pyrosetta into the folding environment. However, I found that in the provided run_e2e script, it asks to conda activate RosettaFold rather than folding. I am wondering which one of the anaconda environments I should use to run. 
Best,
Albert

**Comment by minkbaek** [comment]
RoseTTAFold environment is required to run HHsuite and RoseTTAFold network.
folding environment (where pyrosetta installed) is only needed to run pyrosetta version. If you're going to use e2e version only, you don't need to install folding environment and pyrosetta.
