### ISSUE TITLE
Issue with running hhsearch to completion

### ISSUE THREAD

**Issue by joshsimp** [RosettaCommons/RoseTTAFold#39]
I'm working through getting RoseTTAFold operational using the example sequence. 

HHblits and PSIPRED run to completion, however I encounter an error during hhsearch. In the hhsearch.stderr logfile, it says that the sequence ss_pred contains no residues. I checked t000_.msa0.ss2.a3m and the fastas for >ss_pred and >ss_conf are indeed empty, however the other alignment sequences are still present. 

I tried to fix by recompiling hhsuite using the source binaries as suggested in your FAQ, however that doesn't seem to fix the issue. Does anyone have suggestions on how to move forward?

**Comment by LW-meng** [comment]
Hi joshsimp,

Have you found any solution for it? Many thanks.

Wei

**Comment by maymoona100** [comment]
I am facing the same issue .so when I provide t000_.msa.a3m and t000_.ss2 files it works well and leads to completion .at first it worked fine but after repeating the function for a couple of sequences it is repeating this problem .

**Comment by 275145** [comment]
> I'm working through getting RoseTTAFold operational using the example sequence.
> 
> HHblits and PSIPRED run to completion, however I encounter an error during hhsearch. In the hhsearch.stderr logfile, it says that the sequence ss_pred contains no residues. I checked t000_.msa0.ss2.a3m and the fastas for >ss_pred and >ss_conf are indeed empty, however the other alignment sequences are still present.
> 
> I tried to fix by recompiling hhsuite using the source binaries as suggested in your FAQ, however that doesn't seem to fix the issue. Does anyone have suggestions on how to move forward?

Have you solved this problem? I think you may be able to give me some advice, because I have been troubled by this problem for a long time
