### ISSUE TITLE
Is the md5 hash for the database files available?

### ISSUE THREAD

**Issue by luckydogomg** [RosettaCommons/RoseTTAFold#45]
Hello,

I am just wondering if the md5 hash is available for those large database files and those decompressed files to compare. It took long to download and decompress, just want to make sure the files are intact.
I found that for the 272G bfd database file, wondering if it's available for the other two database files.

Thank you!

**Comment by zemu-unile** [comment]
I got these hashes:
```
6a634dc6eb105c2e9b4cba7bbae93412  bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt.tar.gz
1be0f335e0b003b2455dacbedd4561bf  pdb100_2020Mar11.tar.gz
e8226884850f5ec3d1810e55944413da  UniRef30_2020_06_hhsuite.tar.gz
```

**Comment by luckydogomg** [comment]
> I got these hashes:
> 
> ```
> 6a634dc6eb105c2e9b4cba7bbae93412  bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt.tar.gz
> 1be0f335e0b003b2455dacbedd4561bf  pdb100_2020Mar11.tar.gz
> b14d0aac46d64b8d44729a706d078fe1  pdb100_2021Mar03.tar.gz
> e8226884850f5ec3d1810e55944413da  UniRef30_2020_06_hhsuite.tar.gz
> ```
> 
> Could anyone confirm them?

Thank you!
