### ISSUE TITLE
source code changed after pretrain model submited

### ISSUE THREAD

**Issue by moonblue333** [RosettaCommons/RoseTTAFold#5]
RuntimeError: Error(s) in loading state_dict for RoseTTAFoldModule_e2e:
        Missing key(s) in state_dict: "templ_emb.encoder_L.layers.0.attn_L.to_q.weight", "templ_emb.encoder_L.layers.0.attn_L.to_k.weight",

**Comment by minkbaek** [comment]
I can't reproduce this error. Could you provide more details (including command you used)?

**Comment by moonblue333** [comment]
another error happened, close this firstly.
