### ISSUE TITLE
No GPU available

### ISSUE THREAD

**Issue by Rusfell** [RosettaCommons/RoseTTAFold#54]
Hi,
I want to use RoseTTAFold, but our Linux server has no GPU and only CPUs. Is it OK? Thank you!
Rusfell

**Comment by Rusfell** [comment]
RoseTTAFold runs normally.

**Comment by shenweiyan** [comment]
Excuse me, how did you install it without a GPU? Just run `conda env create -f RoseTTAFold-linux.yml` ? Thank you.
