### ISSUE TITLE
question: model output

### ISSUE THREAD

**Issue by moonblue333** [RosettaCommons/RoseTTAFold#7]
it looks the model only predicts  backbone： N, C, C-alpha; no C-beta and O;  no sidechain?

**Comment by aiXander** [comment]
Correct, the e2e pipeline only generates backbone coordinates (however the paper mentions they're working on a Refine_Module that also models the sidechains). If you need full atom structure models, you're better off running the ```run_pyrosetta_ver.sh``` script, which returns a full atom pdb (downside here is that it requires CPU time to run the FastRelax, and hence its much slower than the e2e version)

**Comment by moonblue333** [comment]
Thanks, close.
