### ISSUE TITLE
Estogram Calculation

### ISSUE THREAD

**Issue by what-is-what** [RosettaCommons/RoseTTAFold#72]
I followed pipeline with example file, input.fa.
It **shows the structure nearly same**, but the LDDT score was totally different like #63 .
LDDT was calculated by estogram and mask, but estogram generated in my pipeline shows almost all 0.
Does anyone solved or faced this problem?

**Comment by ChrisLou-bioinfo** [comment]
I have the same question, but I am not able to solve it even after resetting all
