### ISSUE TITLE
"out of memory" on multi-GPU platform

### ISSUE THREAD

**Issue by IvanWoo22** [RosettaCommons/RoseTTAFold#75]
Hi,

First of all, thanks for sharing such great work. 

I ran this toolkit on the GPU node (consisting of 8 * **V100**) of HPC. Unfortunately, when executing the `predict_e2e.py` script, the program can only call one GPU, which generates an **out of memory** error. 
I consulted with HPC maintenance, and they analyzed that it might be a problem with the script's configuration when executing. 
I wonder if there is a way to solve this problem? Or can I ask to set the parameters for multiple GPUs in the future update?

Here is the command,
```
python RoseTTAFold/network/predict_e2e.py \
-m RoseTTAFold/weights \
-i RoseTTAFold/example/t000_.msa0.a3m \
-o RoseTTAFold/example/t000_.e2e \
--hhr RoseTTAFold/example/t000_.hhr \
--atab RoseTTAFold/example/t000_.atab \
--db RoseTTAFold/pdb100_2021Mar03/pdb100_2021Mar03 1>RoseTTAFold/example/log/network.stdout 2>RoseTTAFold/example/log/network.stderr
```

And log/network.stderr:
```
DGL backend not selected or invalid.  Assuming PyTorch for now.
Using backend: pytorch
...
...
...
  File "/share/home/wangq/wyf/RoseTTAFold/network/equivariant_attention/modules.py", line 303, in forward
    kernel = torch.sum(R * basis[f'{self.degree_in},{self.degree_out}'], -1)
RuntimeError: CUDA out of memory. Tried to allocate 3.43 GiB (GPU 0; 31.72 GiB total capacity; 23.57 GiB already allocated; 2.78 GiB free; 27.29 GiB reserved in total by PyTorch)
```

I appreciate any advice and suggestions. 

Thanks to all~

**Comment by lj734999889** [comment]
I have the same problem. Did you solve this?

**Comment by IvanWoo22** [comment]
> I have the same problem. Did you solve this?

It's not solved yet. I'm waiting for the developers to help with it. Then I finished the calculation with the CPU, although it was prolonged. And I'm not sure if there would be a difference in the results between the two methods except calculation power.

**Comment by lj734999889** [comment]
how to run this pipeline with just cpu?



---Original---
From: ***@***.***&gt;
Date: Fri, Sep 3, 2021 15:11 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [RosettaCommons/RoseTTAFold] "out of memory" on multi-GPU platform (#75)




  
I have the same problem. Did you solve this?
  
It's not solved yet. I'm waiting for the developers to help with it. Then I finished the calculation with the CPU, although it was prolonged. And I'm not sure if there would be a difference in the results between the two methods except calculation power.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by adxyzz** [comment]
Me too, when running protein larger than 400 aa. How to solve it? Could you please teach me how to run it by cpu?

**Comment by adxyzz** [comment]
It seems that, we can reduce the batch_size to solve this problem, but I don't know how to change the batch_size, and which document should be revised?

**Comment by IvanWoo22** [comment]
> how to run this pipeline with just cpu?
> […](#)

Add `--cpu` to the script `predict_e2e.py`.

**Comment by adxyzz** [comment]
> > how to run this pipeline with just cpu?
> > […](#)
> 
> Add `--cpu` to the script `predict_e2e.py`.

Traceback (most recent call last):
  File "/data/RoseTTAFold/network/predict_e2e.py", line 1, in <module>
    --cpu
It seems not work?

**Comment by adxyzz** [comment]
> > how to run this pipeline with just cpu?
> > […](#)
> 
> Add `--cpu` to the script `predict_e2e.py`.

Traceback (most recent call last):
  File "/data/RoseTTAFold/network/predict_e2e.py", line 1, in <module>
    --cpu
NameError: name 'cpu' is not defined
It seems not work?

**Comment by jennifermbui** [comment]
@IvanWoo22.  Most likely that CUDA_VISIBLE_DEVICES is not  assigned.  why don't you do this:
echo $CUDA_VISIBLE_DEVICES 
then use the devices that you're assigned to

**Comment by ragunyrasta** [comment]
> It seems that, we can reduce the batch_size to solve this problem, but I don't know how to change the batch_size, and which document should be revised?

I succeeded in reducing the batch size by hacking around with the code. While it buys a few more residues, it did not help much.  Are there any better solutions? I tried running on a GPU VM with a lot more RAM, but it still fails for a protein with 600 residues. Any advice would be greatly appreciated.

**Comment by 275145** [comment]
> > It seems that, we can reduce the batch_size to solve this problem, but I don't know how to change the batch_size, and which document should be revised?
> 
> I succeeded in reducing the batch size by hacking around with the code. While it buys a few more residues, it did not help much. Are there any better solutions? I tried running on a GPU VM with a lot more RAM, but it still fails for a protein with 600 residues. Any advice would be greatly appreciated.
@ragunyrasta Do you know where to change batch_size, I mean in which py file (or better to the exact line) because I have checked a bunch of information on the internet but they all discuss the impact of setting batch_size bigger or smaller, but they don't mention where to change it, which makes me confused, thanks in advance for your advice

**Comment by 275145** [comment]
> Hi,
> 
> First of all, thanks for sharing such great work.
> 
> I ran this toolkit on the GPU node (consisting of 8 * **V100**) of HPC. Unfortunately, when executing the `predict_e2e.py` script, the program can only call one GPU, which generates an **out of memory** error. I consulted with HPC maintenance, and they analyzed that it might be a problem with the script's configuration when executing. I wonder if there is a way to solve this problem? Or can I ask to set the parameters for multiple GPUs in the future update?
> 
> Here is the command,
> 
> ```
> python RoseTTAFold/network/predict_e2e.py \
> -m RoseTTAFold/weights \
> -i RoseTTAFold/example/t000_.msa0.a3m \
> -o RoseTTAFold/example/t000_.e2e \
> --hhr RoseTTAFold/example/t000_.hhr \
> --atab RoseTTAFold/example/t000_.atab \
> --db RoseTTAFold/pdb100_2021Mar03/pdb100_2021Mar03 1>RoseTTAFold/example/log/network.stdout 2>RoseTTAFold/example/log/network.stderr
> ```
> 
> And log/network.stderr:
> 
> ```
> DGL backend not selected or invalid.  Assuming PyTorch for now.
> Using backend: pytorch
> ...
> ...
> ...
>   File "/share/home/wangq/wyf/RoseTTAFold/network/equivariant_attention/modules.py", line 303, in forward
>     kernel = torch.sum(R * basis[f'{self.degree_in},{self.degree_out}'], -1)
> RuntimeError: CUDA out of memory. Tried to allocate 3.43 GiB (GPU 0; 31.72 GiB total capacity; 23.57 GiB already allocated; 2.78 GiB free; 27.29 GiB reserved in total by PyTorch)
> ```
> 
> I appreciate any advice and suggestions.
> 
> Thanks to all~

@IvanWoo22 Hi, I think I'm having the same problem as you, how long is your input sequence, have you solved the problem , thanks in advance for your advice

**Comment by Yangyang-jane** [comment]
@275145 Hi, I'm having the same problem as you, how long is your input sequence, have you solved the problem , thanks in advance for your advice

**Comment by chukai123** [comment]
Friends, is there a solution to this problem?

**Comment by IvanWoo22** [comment]
I have found two solutions so far, one is choosing the `--cpu` option in `e2e` mode, and the other is using `predict_pyRosetta.py` instead of `predict_e2e.py` for **GPU** computing.
However it is still not clear why `pyRosetta` does not fill up GPU memory.

**Comment by chukai123** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by chukai123** [comment]
> I have found two solutions so far, one is choosing the `--cpu` option in `e2e` mode, and the other is using `predict_pyRosetta.py` instead of `predict_e2e.py` for **GPU** computing. However it is still not clear why `pyRosetta` does not fill up GPU memory.
------------------------------------------------------------------
I used a 365-length sequence to test in predict_e2e.py, and also encountered insufficient GPU, the same in py_Rosetta.py

**Comment by IvanWoo22** [comment]
> I used a 365-length sequence to test in predict_e2e.py, and also encountered insufficient GPU, the same in py_Rosetta.py

Have you confirmed your card model and the CUDA version you are running?

I used py_Rosetta.py on V100, and seqs were about 1k in length.
