### ISSUE TITLE
failed hhsearch

### ISSUE THREAD

**Issue by jessu10** [RosettaCommons/RoseTTAFold#79]
Hello everyone,
I encountered issues while running run_e2e.sh script.

These are the error messages from log files:

>make_ss.stderr
[makemat] FATAL ERROR: Unable to recover checkpoint from t000_.msa0.tmp.chk

Bad psipred pass1 file format!
rm: cannot remove '/home/xx/RoseTTAFold-main/example/aa474/t000_.msa0.a3m.csb.hhblits.ss2': No such file or directory

>hhsearch.stderr
- 14:28:52.127 ERROR: In /opt/conda/conda-bld/hhsuite_1616660820288/work/src/hhalignment.cpp:223: Read:

- 14:28:52.127 ERROR:         sequence ss_pred contains no residues.

Does anyone encounter the same issues and can solve them?
Thank you in advance

**Comment by 275145** [comment]
Have you solved this problem? I have been suffering from similar problems for a long time, thank you in advance for your advice

**Comment by jessu10** [comment]
Hi, I managed to run the RosettaFold, but I found out that my issue was in my fasta file header, which contain special character, not from the RosettaFold or the third party softwares.

**Comment by 275145** [comment]
> Hi, I managed to run the RosettaFold, but I found out that my issue was in my fasta file header, which contain special character, not from the RosettaFold or the third party softwares.
Could you tell me more about the error in the fasta file header, it's important to me

**Comment by jessu10** [comment]
My previous content of fasta file:
>?????
PROTEIN_SEQUENCE

**Comment by 275145** [comment]
Well, then our error may be different, after I use the cat command to check my input.fa it shows
>T1078 Tsp1, Trichoderma virens, 138 residues|
MAAPTPADKSMMAAVPEWTITNLKRVCNAGNTSCTWTFGVDTHLATATSCTYVKANANASQASGGPVTCGPYTITSSWSGQFGPNNGFTTFAVTDFSKKLIVWPAYTDVQVQAGKVVSPNQSYAPANLPLEHHHHHH

**Comment by jessu10** [comment]
Yeah, maybe you can try to reinstall the RoseTTAFold again without changing anything except the directory part.

**Comment by zrqiao** [comment]
> My previous content of fasta file:
> 
> > ?????
> > PROTEIN_SEQUENCE

This is exactly the problem I was facing. Thanks for this!
