### ISSUE TITLE
Running predictions for Protein-Protein complexes

### ISSUE THREAD

**Issue by aiXander** [RosettaCommons/RoseTTAFold#9]
Hi, first of all thank you for open sourcing this amazing tool!

The paper mentions that

> The final layer of the end-to-end version of our 3-track network generates 3D structure
> models by combining features from discontinuous crops of the protein sequence (two segments
> of the protein with a chain break between them). Because the network can seamlessly handle
> chain breaks, it can be readily utilized to predict the structure of protein-protein complexes
> directly from sequence information.

Looking at the code in ```Refine_module.py``` and ```predict_e2e.py```, it looks like there are quite a lot of details to get right and many ways to screw up how the information from two disjoint chains should be merged. According to the supplementary material there's also _`changes in the positional encoding`_ needed for this to work (the +200 offset).

Is there an example script or some guidelines that you could share that shows how to properly do a structure prediction for a Protein-Protein complex?

Finally, I was wondering if any experiments were done trying to estimate binding affinity scores from the hidden layer activations of the Refine_Module? This would be a very useful extension for doing protein design...

**Comment by minkbaek** [comment]
We're planning to release scripts for complex structure modeling with some modeling guidelines within this week (but, fingers crossed!).

**Comment by minkbaek** [comment]
Complex modeling scripts are added now!

For the last question (binding affinity prediction), we haven't tried it yet.

**Comment by Lsz-20** [comment]
@minkbaek I still have some questions about the complex model especially the 2track.
it seems that the 2track has only the npz output without the pdb?
This seems to be different from the paper?
Thanks!
